CREATE TABLE LOTTERY_USER (
    ID NUMBER(20),
    PASSWORD VARCHAR2(255),
    ROLE VARCHAR2(255),
    USERNAME VARCHAR2(255)
);

CREATE TABLE WEEKLY_DRAW (
    ID NUMBER(20),
    REDIS_ID VARCHAR2(255),
    DRAWDATE DATE,
    FIVE_MATCH NUMBER(20),
    FIVE_MATCH_PRIZE NUMBER(20),
    FOUR_MATCH NUMBER(20),
    FOUR_MATCH_PRIZE NUMBER(20),
    THREE_MATCH NUMBER(20),
    THREE_MATCH_PRIZE NUMBER(20),
    TWO_MATCH NUMBER(20),
    TWO_MATCH_PRIZE NUMBER(20),
    FIRST NUMBER(2),
    TWO NUMBER(2),
    THIRD NUMBER(2),
    FOURTH NUMBER(2),
    FIFTH NUMBER(2)
);

